Repository sphinx-contrib/sphinxcontrib-towncrier, pull requests merged in 2020-08, with the labels that each got.

#6 Refactor sphinx RST parsing in towncrier extension
  src/sphinxcontrib/towncrier/__init__.py
Labels: enhancement

#23 📝 Rebuild any documents using the directive
  src/sphinxcontrib/towncrier/__init__.py
Labels: bug, enhancement

#21 Configure pre-commit
  .pre-commit-config.yaml
  .pylintrc
  .yamllint
  src/sphinxcontrib/towncrier/_version.py
Labels: enhancement

#24 Add a tox config with `build-dists` env
  tox.ini
Labels: enhancement

#25 Fix missed pylint errors
  src/sphinxcontrib/towncrier/__init__.py
Labels: bug

#26 Add a `lint` toxenv
  tox.ini
Labels: enhancement

#27 Fix indentation to avoid pylint's C0330 error
  src/sphinxcontrib/towncrier/__init__.py
Labels: bug

#29 Fix build-dists command flow to ignore `No such file or directory` error
  tox.ini
Labels: bug

#28 Add GitHub Actions workflows for `toxenv:lint`
  .github/workflows/tox-linters.yaml
Labels: enhancement

#33 Add `mypy` hook to pre-commit
  .pre-commit-config.yaml
  mypy.ini
  src/sphinxcontrib/towncrier/__init__.py
  src/sphinxcontrib/towncrier/_scm_version.pyi
Labels: enhancement

#34 Improve pylint config with project-specific settings
  .pylintrc
Labels: enhancement

#32 Add `isort` hook to pre-commit
  .isort.cfg
  .pre-commit-config.yaml
Labels: enhancement
